### ISSUE TITLE
Visual Studio Code

### ISSUE THREAD

**Issue by pcwa-ahendricks** [jenskutilek/sudo-font#11]
I haven't been able to get this font to work well with Microsoft Visual Studio Code. Any ideas? Specifically, there is no syntax highlighting.
<img width="905" alt="Screen Shot 2019-08-02 at 4 59 23 PM" src="https://user-images.githubusercontent.com/19213787/62404117-ef619a00-b546-11e9-922d-0426aac39ae4.png">

**Comment by jenskutilek** [comment]
Is that on Mac? I don't know how a font could cause the syntax highlighting to stop working ...

**Comment by jenskutilek** [comment]
I think it may be caused by the colorized glyphs added in a recent update. The system seems to think that it is a color font and thus doesn't apply any other coloring to the text. You can try installing [the previous release](https://github.com/jenskutilek/sudo-font/releases/tag/v0.38) which didn't contain the color glyphs.

**Comment by pcwa-ahendricks** [comment]
Excellent. [v0.38](https://github.com/jenskutilek/sudo-font/releases/tag/v0.38) works as expected. On a side note great font! Thanks for sharing.
